version: "3.9"

services:
  web:
    build: .
    container_name: securevote_web
    ports:
      - "5000:5000"     # host:container
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/securevote
    depends_on:
      - db
    volumes:
      - .:/app          # for live code updates during dev

  db:
    image: postgres:15
    container_name: securevote_db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=securevote
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
